# Generated by Django 6.1 on 2026-08-27 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0002_alter_shopuser_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopuser',
            name='business_type',
            field=models.CharField(choices=[('General', 'General Store / Hardware'), ('Food', 'Food / Pharmacy / FMCG'), ('Electronics', 'Electronics / Mobile / IT'), ('Apparel', 'Apparel / Footwear')], default='General', max_length=50),
        ),
        migrations.AlterField(
            model_name='shopuser',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
