# Generated by Django 6.1 on 2026-08-31 13:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0003_shopuser_business_type_alter_shopuser_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopuser',
            name='is_shop_staff',
            field=models.BooleanField(default=False, help_text='ટીક કરો જો આ એકાઉન્ટ દુકાનના સ્ટાફ/વર્કરનું હોય'),
        ),
        migrations.AddField(
            model_name='shopuser',
            name='parent_shop',
            field=models.ForeignKey(blank=True, help_text='જો આ સ્ટાફ હોય, તો તેના મુખ્ય માલિક (Owner) કયા છે?', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff_members', to=settings.AUTH_USER_MODEL),
        ),
    ]
