# Generated by Django 6.1 on 2026-08-29 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0004_product_color_product_company_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='company_barcode',
            field=models.CharField(blank=True, help_text='કંપનીનો EAN/UPC બારકોડ', max_length=100, null=True),
        ),
    ]
