# Generated by Django 6.1 on 2026-08-31 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0006_customerprofile_ledgertransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='payment_mode',
            field=models.CharField(choices=[('CASH', 'Cash (રોકડા)'), ('UPI', 'UPI (GPay/PhonePe)'), ('CARD', 'Card (ક્રેડિટ/ડેબિટ)'), ('UNPAID', 'Udhar (ખાતાવહીમાં બાકી)')], default='CASH', max_length=20),
        ),
    ]
